### ISSUE TITLE
Paper of CT report generation

### ISSUE THREAD

**Issue by zhi-xuan-chen** [synlp/RRG-Review#3]
Thank you for your job!

I would like to ask if this repository will share some work on CT report generation?

**Comment by AlonzoLeeeooo** [comment]
Thank you for your attention!

**Comment by AlonzoLeeeooo** [comment]
Hi @zhi-xuan-chen ,

Thank you for your attention! The EMNLP 2022 paper titled "Factual Accuracy is not Enough: Planning Consistent Description Order for Radiology Report Generation" is a particular study that focuses on the scenario of generating radiology reports for CT liver images. You can refer to the paper [here](https://aclanthology.org/2022.emnlp-main.480/).

If you have other related papers, please feel free to let us know. We will update the GitHub repository as well as our survey paper accordingly.

Best

**Comment by zhi-xuan-chen** [comment]
OK, thank you for your sharing!
